title = "名古屋サンプルブログ"
baseURL = "https://curegit.github.io/nagoya-example/"
theme = "nagoya"
paginate = 5
paginatePath = ""
languageCode = "ja"
DefaultContentLanguage = "ja"
hasCJKLanguage = true
enableInlineShortcodes = true
enableRobotsTXT = true
cleanDestinationDir = true
enableGitInfo = true

[params]
  treeRoot = "posts"
  author = "高橋 元"
  authorLink = "https://github.com/curegit/nagoya"
  description = "Hugo 日本語テーマ「名古屋」のサンプルサイト"
  keywords = ["ブログ", "Hugo", "名古屋"]
  images = ["bio.png"]

[frontmatter]
  date = ["date", "publishDate", ":git", ":fileModTime"]
  lastmod = ["lastmod", ":git", ":fileModTime"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

    [markup.goldmark.extensions]
      [markup.goldmark.extensions.cjk]
        enable = true
        eastAsianLineBreaks = true

  [markup.highlight]
    codeFences = true
    style = "modus-vivendi"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"
  search = "search"
